<?php

$idioma = array(
    "titulo" => "Bienvenido a La Delicia",
    "descubre" => "Descubre nuestra selección de platos mediterráneos...",
    "reservar" => "Reservar ahora",
    "cerrar_sesion" => "Cerrar Sesión",
    "iniciar_sesion" => "Iniciar Sesión",
    "registrarse" => "Registrarse",
    "menu" => "Menú",
    "nosotros" => "Sobre Nosotros",
    "contacto" => "Contacto",
    "bienvenidos" => "Bienvenidos a La Delicia",
    "disfruta" => "Disfruta de la auténtica cocina mediterránea en un ambiente acogedor. Reserva tu mesa ahora y vive una experiencia gastronómica inolvidable.",
    "cocina_exquisita" => "Cocina Exquisita",
    "cocina_exquisita_desc" => "Nuestros chefs preparan platos con los ingredientes más frescos y de la mejor calidad.",
    "ambiente_acogedor" => "Ambiente Acogedor",
    "ambiente_acogedor_desc" => "Un espacio diseñado para que disfrutes de momentos especiales con tus seres queridos.",
    "reserva_facil" => "Reserva Fácil",
    "reserva_facil_desc" => "Reserva tu mesa en minutos a través de nuestro sistema online.",
    "nuestro_menu" => "Nuestro Menú",
    "nuestro_menu_desc" => "Descubre nuestra selección de platos mediterráneos, preparados con ingredientes frescos y de la mejor calidad.",
    "paella_valenciana" => "Paella Valenciana",
    "paella_valenciana_desc" => "Arroz, azafrán, pollo, conejo, judías verdes, garrofón y pimentón.",
    "risotto_setas" => "Risotto de Setas",
    "risotto_setas_desc" => "Arroz arborio, setas variadas, cebolla, vino blanco y queso parmesano.",
    "pasta_pesto" => "Pasta al Pesto",
    "pasta_pesto_desc" => "Pasta fresca, albahaca, piñones, ajo, queso parmesano y aceite de oliva.",
    "dorada_sal" => "Dorada a la Sal",
    "dorada_sal_desc" => "Dorada fresca, sal marina, hierbas aromáticas y aceite de oliva virgen extra.",
    "nuestros_servicios" => "Nuestros Servicios",
    "nuestros_servicios_desc" => "Descubre los servicios exclusivos que ofrecemos para hacer de tu experiencia algo inolvidable.",
    "horario" => "Horario",
    "horario_lunes_jueves" => "Lunes - Jueves:",
    "horario_viernes_sabado" => "Viernes - Sábado:",
    "horario_domingo" => "Domingo:",
    "contacto_titulo" => "Contacto",
    "contacto_direccion" => "Calle Principal 123, Ciudad",
    "contacto_telefono" => "+34 123 456 789",
    "contacto_email" => "info@ladelicia.com",
    "siguenos" => "Síguenos",
    "reserva_ahora" => "Reserva Ahora"
);

?>