<?php
$idioma = array(
    "titulo" => "Welcome to La Delicia",
    "descubre" => "Discover our selection of Mediterranean dishes...",
    "reservar" => "Book now",
    "cerrar_sesion" => "Log Out",
    "iniciar_sesion" => "Log In",
    "registrarse" => "Sign Up",
    "menu" => "Menu",
    "nosotros" => "About Us",
    "contacto" => "Contact",
    "bienvenidos" => "Welcome to La Delicia",
    "disfruta" => "Enjoy authentic Mediterranean cuisine in a cozy atmosphere. Book your table now and live an unforgettable gastronomic experience.",
    "cocina_exquisita" => "Exquisite Cuisine",
    "cocina_exquisita_desc" => "Our chefs prepare dishes with the freshest and highest quality ingredients.",
    "ambiente_acogedor" => "Cozy Atmosphere",
    "ambiente_acogedor_desc" => "A space designed for you to enjoy special moments with your loved ones.",
    "reserva_facil" => "Easy Reservation",
    "reserva_facil_desc" => "Book your table in minutes through our online system.",
    "nuestro_menu" => "Our Menu",
    "nuestro_menu_desc" => "Discover our selection of Mediterranean dishes, prepared with fresh and high-quality ingredients.",
    "paella_valenciana" => "Valencian Paella",
    "paella_valenciana_desc" => "Rice, saffron, chicken, rabbit, green beans, garrofón, and paprika.",
    "risotto_setas" => "Mushroom Risotto",
    "risotto_setas_desc" => "Arborio rice, assorted mushrooms, onion, white wine, and parmesan cheese.",
    "pasta_pesto" => "Pasta al Pesto",
    "pasta_pesto_desc" => "Fresh pasta, basil, pine nuts, garlic, parmesan cheese, and olive oil.",
    "dorada_sal" => "Sea Bream with Salt",
    "dorada_sal_desc" => "Fresh sea bream, sea salt, aromatic herbs, and extra virgin olive oil.",
    "nuestros_servicios" => "Our Services",
    "nuestros_servicios_desc" => "Discover the exclusive services we offer to make your experience unforgettable.",
    "horario" => "Opening Hours",
    "horario_lunes_jueves" => "Monday - Thursday:",
    "horario_viernes_sabado" => "Friday - Saturday:",
    "horario_domingo" => "Sunday:",
    "contacto_titulo" => "Contact",
    "contacto_direccion" => "Main Street 123, City",
    "contacto_telefono" => "+34 123 456 789",
    "contacto_email" => "info@ladelicia.com",
    "siguenos" => "Follow Us",
    "reserva_ahora" => "Reserve Now"
);

?>